### ISSUE TITLE
Gamepad is not supported properly

### ISSUE THREAD

**Issue by goldenxp** [onyx-deveIopment/Juicy-Player-Controller#2]
Left stick works but right stick does not.

**Comment by AndrewCromar** [comment]
Hello, thanks for letting me know. I will get to fixing asap.

**Comment by goldenxp** [comment]
I tested both lemon and orange demos and both seem to be hardcoded to the mouse.

**Comment by AndrewCromar** [comment]
Okay thank you I will work on it.

**Comment by AndrewCromar** [comment]
I fixed the bug while also updating to the Unity Input System. This way you can more easily change the controls to your liking.

I have changed a few things you might want to know:
- You can now download either the zip file or the unityasset file which can be easier to install.
- Make sure you download the Unity Input System package from the package manager or it will not work.

Thanks for letting me know about this issue. If you find anymore issues please let me know, I would like to make this package as good as possible.

**Comment by goldenxp** [comment]
Confirmed it's fixed. Good call on using Input System. I can tweak the file and modify sprints and other inputs 👍 
Appreciate the speed at which this was fixed!

**Comment by AndrewCromar** [comment]
No problem! If you don't mind me asking, how did you come across this project?

**Comment by goldenxp** [comment]
I searched for unity controller while sorting as recently updated.

**Comment by AndrewCromar** [comment]
Awesome! Thanks for letting me know.
